# Welcome to Jekyll!
#

# Site settings
title: 김나은의 포토폴리오
description: |
  Another fine responsive  
  site template freebie  
  crafted by [HTML5 UP](http://html5up.net)
owner: kim naeun
first_published: 2016 # if migrating another site, the year of your first publish
email: kne0140@daum.net
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
social:
  github: https://github.com/naeunkim1227
  email: kne0140@daum.net
# Build settings
markdown: kramdown
#sass:
#  style: compressed
